    opt h-

NAMES_MEN
    dta d'Piotr       '    ; 1
    dta d'Krzysztof   '    ; 2
    dta d'Andrzej     '    ; 3
    dta d'Tomasz      '    ; 4
    dta d'Jan         '    ; 5
    dta d'Paweł       '    ; 6
    dta d'Michał      '    ; 7
    dta d'Marcin      '    ; 8
    dta d'Stanisław   '    ; 9
    dta d'Jakub       '    ; 10
    dta d'Adam        '    ; 11
    dta d'Marek       '    ; 12
    dta d'Łukasz      '    ; 13
    dta d'Grzegorz    '    ; 14
    dta d'Mateusz     '    ; 15
    dta d'Wojciech    '    ; 16
    dta d'Mariusz     '    ; 17
    dta d'Dariusz     '    ; 18
    dta d'Zbigniew    '    ; 19
    dta d'Jerzy       '    ; 20
    dta d'Maciej      '    ; 21
    dta d'Rafał       '    ; 22
    dta d'Robert      '    ; 23
    dta d'Kamil       '    ; 24
    dta d'Józef       '    ; 25
    dta d'Jacek       '    ; 26
    dta d'Dawid       '    ; 27
    dta d'Tadeusz     '    ; 28
    dta d'Ryszard     '    ; 29
    dta d'Szymon      '    ; 30
    dta d'Kacper      '    ; 31
    dta d'Bartosz     '    ; 32
    dta d'Janusz      '    ; 33
    dta d'Jarosław    '    ; 34
    dta d'Sławomir    '    ; 35
    dta d'Mirosław    '    ; 36
    dta d'Artur       '    ; 37
    dta d'Henryk      '    ; 38
    dta d'Sebastian   '    ; 39
    dta d'Damian      '    ; 40
    dta d'Patryk      '    ; 41
    dta d'Kazimierz   '    ; 42
    dta d'Przemysław  '    ; 43
    dta d'Daniel      '    ; 44
    dta d'Karol       '    ; 45
    dta d'Roman       '    ; 46
    dta d'Marian      '    ; 47
    dta d'Wiesław     '    ; 48
    dta d'Filip       '    ; 49
    dta d'Antoni      '    ; 50
    dta d'Adrian      '    ; 51
    dta d'Arkadiusz   '    ; 52
    dta d'Aleksander  '    ; 53
    dta d'Dominik     '    ; 54
    dta d'Bartłomiej  '    ; 55
    dta d'Franciszek  '    ; 56
    dta d'Leszek      '    ; 57
    dta d'Mikołaj     '    ; 58
    dta d'Waldemar    '    ; 59
    dta d'Krystian    '    ; 60
    dta d'Zdzisław    '    ; 61
    dta d'Wiktor      '    ; 62
    dta d'Radosław    '    ; 63
    dta d'Bogdan      '    ; 64
    dta d'Edward      '    ; 65
    dta d'Mieczysław  '    ; 66
    dta d'Konrad      '    ; 67
    dta d'Władysław   '    ; 68
    dta d'Hubert      '    ; 69
    dta d'Czesław     '    ; 70
    dta d'Igor        '    ; 71
    dta d'Eugeniusz   '    ; 72
    dta d'Oskar       '    ; 73
    dta d'Stefan      '    ; 74
    dta d'Bogusław    '    ; 75
    dta d'Marcel      '    ; 76
    dta d'Ireneusz    '    ; 77
    dta d'Zygmunt     '    ; 78
    dta d'Maksymilian '    ; 79
    dta d'Witold      '    ; 80
    dta d'Miłosz      '    ; 81
    dta d'Sylwester   '    ; 82
    dta d'Włodzimierz '    ; 83
    dta d'Zenon       '    ; 84
    dta d'Oliwier     '    ; 85
    dta d'Alan        '    ; 86
    dta d'Cezary      '    ; 87
    dta d'Nikodem     '    ; 88
    dta d'Leon        '    ; 89
    dta d'Norbert     '    ; 90
    dta d'Oleksandr   '    ; 91
    dta d'Gabriel     '    ; 92
    dta d'Julian      '    ; 93
    dta d'Błażej      '    ; 94
    dta d'Fabian      '    ; 95
    dta d'Ignacy      '    ; 96
    dta d'Tymoteusz   '    ; 97
    dta d'Eryk        '    ; 98
    dta d'Emil        '    ; 99
    dta d'Bronisław   '    ; 100
    dta d'Wacław      '    ; 101
    dta d'Lech        '    ; 102
    dta d'Serhii      '    ; 103
    dta d'Tymon       '    ; 104
    dta d'Andrii      '    ; 105
    dta d'Volodymyr   '    ; 106
    dta d'Bolesław    '    ; 107
    dta d'Bernard     '    ; 108
    dta d'Edmund      '    ; 109
    dta d'Remigiusz   '    ; 110
    dta d'Ksawery     '    ; 111
    dta d'Natan       '    ; 112
    dta d'Dmytro      '    ; 113
    dta d'Olaf        '    ; 114
    dta d'Ivan        '    ; 115
    dta d'Lucjan      '    ; 116
    dta d'Borys       '    ; 117
    dta d'Romuald     '    ; 118
    dta d'Kajetan     '    ; 119
    dta d'Mykola      '    ; 120
    dta d'Vitalii     '    ; 121
    dta d'Vasyl       '    ; 122
    dta d'Szczepan    '    ; 123
    dta d'Ihor        '    ; 124
    dta d'Albert      '    ; 125
    dta d'Kuba        '    ; 126
    dta d'Gracjan     '    ; 127
    dta d'Seweryn     '    ; 128
    dta d'Tobiasz     '    ; 129
    dta d'Maksym      '    ; 130
    dta d'Alfred      '    ; 131
    dta d'Yurii       '    ; 132
    dta d'Ludwik      '    ; 133
    dta d'Oleh        '    ; 134
    dta d'Joachim     '    ; 135
    dta d'Viktor      '    ; 136
    dta d'Lesław      '    ; 137
    dta d'Bogumił     '    ; 138
    dta d'Mykhailo    '    ; 139
    dta d'Ernest      '    ; 140
    dta d'Gerard      '    ; 141
    dta d'Bruno       '    ; 142
    dta d'Kornel      '    ; 143
    dta d'Olivier     '    ; 144
    dta d'Feliks      '    ; 145
    dta d'Bohdan      '    ; 146
    dta d'Jędrzej     '    ; 147
    dta d'Alexander   '    ; 148
    dta d'Alojzy      '    ; 149
    dta d'Alex        '    ; 150
    dta d'Vladyslav   '    ; 151
    dta d'Leonard     '    ; 152
    dta d'Oleksii     '    ; 153
    dta d'Juliusz     '    ; 154
    dta d'David       '    ; 155
    dta d'Klaudiusz   '    ; 156
    dta d'Ruslan      '    ; 157
    dta d'Aleks       '    ; 158
    dta d'Benedykt    '    ; 159
    dta d'Dorian      '    ; 160
    dta d'Rajmund     '    ; 161
    dta d'Teodor      '    ; 162
    dta d'Oliver      '    ; 163
    dta d'Martin      '    ; 164
    dta d'Pavlo       '    ; 165
    dta d'Cyprian     '    ; 166
    dta d'Nataniel    '    ; 167
    dta d'Konstanty   '    ; 168
    dta d'Rudolf      '    ; 169
    dta d'Denys       '    ; 170
    dta d'Denis       '    ; 171
    dta d'Anatolii    '    ; 172
    dta d'Vadym       '    ; 173
    dta d'Artem       '    ; 174
    dta d'Brajan      '    ; 175
    dta d'Gustaw      '    ; 176
    dta d'Michael     '    ; 177
    dta d'Hieronim    '    ; 178
    dta d'Petro       '    ; 179
    dta d'Yaroslav    '    ; 180
    dta d'Samuel      '    ; 181
    dta d'Wincenty    '    ; 182
    dta d'Mieszko     '    ; 183
    dta d'Marceli     '    ; 184
    dta d'Florian     '    ; 185
    dta d'Zygfryd     '    ; 186
    dta d'Yevhen      '    ; 187
    dta d'Erwin       '    ; 188
    dta d'Kevin       '    ; 189
    dta d'Milan       '    ; 190
    dta d'Ariel       '    ; 191
    dta d'Fryderyk    '    ; 192
    dta d'Iwo         '    ; 193
    dta d'Valerii     '    ; 194
    dta d'Taras       '    ; 195
    dta d'Anton       '    ; 196
    dta d'Aleksy      '    ; 197
    dta d'Aliaksandr  '    ; 198
    dta d'Yevhenii    '    ; 199
    dta d'Beniamin    '    ; 200
    dta d'Oleg        '    ; 201
    dta d'Roland      '    ; 202
    dta d'Sergiusz    '    ; 203
    dta d'Kordian     '    ; 204
    dta d'Andrei      '    ; 205
    dta d'Walenty     '    ; 206
    dta d'Jeremi      '    ; 207
    dta d'Adolf       '    ; 208
    dta d'Amadeusz    '    ; 209
    dta d'Viacheslav  '    ; 210
    dta d'Augustyn    '    ; 211
    dta d'Olgierd     '    ; 212
    dta d'Brunon      '    ; 213
    dta d'Stanislav   '    ; 214
    dta d'Patrick     '    ; 215
    dta d'Sergii      '    ; 216
    dta d'Leopold     '    ; 217
    dta d'Maximilian  '    ; 218
    dta d'Emilian     '    ; 219
    dta d'Kewin       '    ; 220
    dta d'Thomas      '    ; 221
    dta d'Kostiantyn  '    ; 222
    dta d'Herbert     '    ; 223
    dta d'Albin       '    ; 224
    dta d'Siarhei     '    ; 225
    dta d'Oscar       '    ; 226
    dta d'Alfons      '    ; 227
    dta d'Arnold      '    ; 228
    dta d'Nicolas     '    ; 229
    dta d'Victor      '    ; 230
    dta d'Oliwer      '    ; 231
    dta d'Wilhelm     '    ; 232
    dta d'Maurycy     '    ; 233
    dta d'Stepan      '    ; 234
    dta d'Anatol      '    ; 235
    dta d'Andriy      '    ; 236
    dta d'Valentyn    '    ; 237
    dta d'Helmut      '    ; 238
    dta d'Peter       '    ; 239
    dta d'Dzmitry     '    ; 240
    dta d'Oktawian    '    ; 241
    dta d'Walter      '    ; 242
    dta d'Ginter      '    ; 243
    dta d'Manfred     '    ; 244
    dta d'Edwin       '    ; 245
    dta d'Teofil      '    ; 246
    dta d'Emanuel     '    ; 247
    dta d'Nazar       '    ; 248
    dta d'Korneliusz  '    ; 249
    dta d'Jeremiasz   '    ; 250
    dta d'Werner      '    ; 251
    dta d'Jonasz      '    ; 252
    dta d'Kryspin     '    ; 253
    dta d'Mark        '    ; 254
    dta d'Illia       '    ; 255
    dta d'Leo         '    ; 256
    dta d'Eduard      '    ; 257
    dta d'Walerian    '    ; 258
    dta d'Nathan      '    ; 259
    dta d'Christian   '    ; 260
    dta d'Jonatan     '    ; 261
    dta d'Kasper      '    ; 262
    dta d'Pavel       '    ; 263
    dta d'Benjamin    '    ; 264
    dta d'Ziemowit    '    ; 265
    dta d'Lechosław   '    ; 266
    dta d'Leonid      '    ; 267
    dta d'Xavier      '    ; 268
    dta d'Nikolas     '    ; 269
    dta d'Jacob       '    ; 270
    dta d'Max         '    ; 271
    dta d'Tytus       '    ; 272
    dta d'Iurii       '    ; 273
    dta d'Miron       '    ; 274
    dta d'Patrycjusz  '    ; 275
    dta d'Klemens     '    ; 276
    dta d'Yuriy       '    ; 277
    dta d'Ferdynand   '    ; 278
    dta d'Aron        '    ; 279
    dta d'Paul        '    ; 280
    dta d'Longin      '    ; 281
    dta d'Ksawier     '    ; 282
    dta d'Hugo        '    ; 283
    dta d'Philip      '    ; 284
    dta d'Matthew     '    ; 285
    dta d'Horst       '    ; 286
    dta d'Wawrzyniec  '    ; 287
    dta d'Jacenty     '    ; 288
    dta d'Andreas     '    ; 289
    dta d'Rostyslav   '    ; 290
    dta d'Christopher '    ; 291
    dta d'Eliasz      '    ; 292
    dta d'Dionizy     '    ; 293
    dta d'Izydor      '    ; 294
    dta d'John        '    ; 295
    dta d'Anthony     '    ; 296
    dta d'Marco       '    ; 297
    dta d'Łucjan      '    ; 298
    dta d'Mykhaylo    '    ; 299
    dta d'Yury        '    ; 300
    dta d'Vitali      '    ; 301
    dta d'Uladzimir   '    ; 302
    dta d'Aliaksei    '    ; 303
    dta d'Roch        '    ; 304
    dta d'Kasjan      '    ; 305
    dta d'Ewald       '    ; 306
    dta d'Danylo      '    ; 307
    dta d'Eligiusz    '    ; 308
    dta d'Simon       '    ; 309
    dta d'Gerhard     '    ; 310
    dta d'Jaromir     '    ; 311
    dta d'Maks        '    ; 312
    dta d'Rafael      '    ; 313
    dta d'Mykyta      '    ; 314
    dta d'Mohamed     '    ; 315
    dta d'Brian       '    ; 316
    dta d'Hennadii    '    ; 317
    dta d'Maksim      '    ; 318
    dta d'Nazarii     '    ; 319
    dta d'Kyrylo      '    ; 320
    dta d'Vitaliy     '    ; 321
    dta d'Ali         '    ; 322
    dta d'Nicholas    '    ; 323
    dta d'Jonathan    '    ; 324
    dta d'Vincent     '    ; 325
    dta d'Yauheni     '    ; 326
    dta d'Radomir     '    ; 327
    dta d'Serhiy      '    ; 328
    dta d'Mikhail     '    ; 329
    dta d'Bazyli      '    ; 330
    dta d'Zbysław     '    ; 331
    dta d'Viktar      '    ; 332
    dta d'Ion         '    ; 333
    dta d'Antonio     '    ; 334
    dta d'Wit         '    ; 335
    dta d'Richard     '    ; 336
    dta d'Kosma       '    ; 337
    dta d'Giorgi      '    ; 338
    dta d'Roger       '    ; 339
    dta d'William     '    ; 340
    dta d'Aleh        '    ; 341
    dta d'Dennis      '    ; 342
    dta d'Vladimir    '    ; 343
    dta d'Ihar        '    ; 344
    dta d'Lukas       '    ; 345
    dta d'Markus      '    ; 346
    dta d'Orest       '    ; 347
    dta d'Eric        '    ; 348
    dta d'Nikita      '    ; 349
    dta d'Hryhorii    '    ; 350
    dta d'Bonifacy    '    ; 351
    dta d'Lucas       '    ; 352
    dta d'Jordan      '    ; 353
    dta d'James       '    ; 354
    dta d'Andrew      '    ; 355
    dta d'Leonardo    '    ; 356
    dta d'Aaron       '    ; 357
    dta d'August      '    ; 358
    dta d'Pascal      '    ; 359
    dta d'Frank       '    ; 360
    dta d'Mikalai     '    ; 361
    dta d'Yehor       '    ; 362
    dta d'Zbyszek     '    ; 363
    dta d'Mario       '    ; 364
    dta d'Cyryl       '    ; 365
    dta d'Daniil      '    ; 366
    dta d'Dominic     '    ; 367
    dta d'Brayan      '    ; 368
    dta d'Diego       '    ; 369
    dta d'Myroslav    '    ; 370
    dta d'Klaus       '    ; 371
    dta d'Aleksandr   '    ; 372
    dta d'Ahmed       '    ; 373
    dta d'Bogusz      '    ; 374
    dta d'Arthur      '    ; 375
    dta d'Wolfgang    '    ; 376
    dta d'Erik        '    ; 377
    dta d'Sergiy      '    ; 378
    dta d'Carlos      '    ; 379
    dta d'Valery      '    ; 380
    dta d'Allan       '    ; 381
    dta d'Joseph      '    ; 382
    dta d'Bryan       '    ; 383
    dta d'Donat       '    ; 384
    dta d'Sviatoslav  '    ; 385
    dta d'Matteo      '    ; 386
    dta d'Dymitr      '    ; 387
    dta d'Alessandro  '    ; 388
    dta d'Luca        '    ; 389
    dta d'Heronim     '    ; 390
    dta d'Nathaniel   '    ; 391
    dta d'Francesco   '    ; 392
    dta d'Ivo         '    ; 393
    dta d'Lubomir     '    ; 394
    dta d'Uladzislau  '    ; 395
    dta d'Juan        '    ; 396
    dta d'Kurt        '    ; 397
    dta d'Liubomyr    '    ; 398
    dta d'Dzianis     '    ; 399
    dta d'Dieter      '    ; 400
    dta d'Jose        '    ; 401
    dta d'Alexandre   '    ; 402
    dta d'Benon       '    ; 403
    dta d'Serghei     '    ; 404
    dta d'Aureliusz   '    ; 405
    dta d'Manuel      '    ; 406
    dta d'Mihail      '    ; 407
    dta d'Marko       '    ; 408
    dta d'Edgar       '    ; 409
    dta d'Mehmet      '    ; 410
    dta d'Joshua      '    ; 411
    dta d'Amir        '    ; 412
    dta d'Maxymilian  '    ; 413
    dta d'Jakob       '    ; 414
    dta d'Anatoli     '    ; 415
    dta d'Maxim       '    ; 416
    dta d'Euzebiusz   '    ; 417
    dta d'Omar        '    ; 418
    dta d'Ryan        '    ; 419
    dta d'Luis        '    ; 420
    dta d'Hans        '    ; 421
    dta d'Alexandr    '    ; 422
    dta d'Roberto     '    ; 423
    dta d'Karim       '    ; 424
    dta d'Gniewomir   '    ; 425
    dta d'Anatoliy    '    ; 426
    dta d'Zbyszko     '    ; 427
    dta d'Ievgen      '    ; 428
    dta d'Raman       '    ; 429
    dta d'Colin       '    ; 430
    dta d'Justin      '    ; 431
    dta d'Ian         '    ; 432
    dta d'Vadzim      '    ; 433
    dta d'Herman      '    ; 434
    dta d'Yan         '    ; 435
    dta d'Chrystian   '    ; 436
    dta d'Alexandru   '    ; 437
    dta d'Ricardo     '    ; 438
    dta d'Hilary      '    ; 439
    dta d'Liam        '    ; 440
    dta d'Mustafa     '    ; 441
    dta d'Matthias    '    ; 442
    dta d'Andrea      '    ; 443
    dta d'Armin       '    ; 444
    dta d'Philipp     '    ; 445
    dta d'Vasile      '    ; 446
    dta d'Davyd       '    ; 447
    dta d'Felix       '    ; 448
    dta d'Mohammad    '    ; 449
    dta d'Noah        '    ; 450
    dta d'Kai         '    ; 451
    dta d'Zachariasz  '    ; 452
    dta d'Tristan     '    ; 453
    dta d'Fedir       '    ; 454
    dta d'January     '    ; 455
    dta d'Iaroslav    '    ; 456
    dta d'Bartek      '    ; 457
    dta d'Narcyz      '    ; 458
    dta d'Nicolae     '    ; 459
    dta d'Muhammad    '    ; 460
    dta d'Reinhold    '    ; 461
    dta d'Rajnold     '    ; 462
    dta d'Cristian    '    ; 463
    dta d'Idzi        '    ; 464
    dta d'Angelo      '    ; 465
    dta d'George      '    ; 466
    dta d'Pablo       '    ; 467
    dta d'Harald      '    ; 468
    dta d'Ronald      '    ; 469
    dta d'Mohammed    '    ; 470
    dta d'Henry       '    ; 471
    dta d'Giuseppe    '    ; 472
    dta d'Zenobiusz   '    ; 473
    dta d'Kristian    '    ; 474
    dta d'Ilya        '    ; 475
    dta d'Arsen       '    ; 476
    dta d'Justyn      '    ; 477
    dta d'Michal      '    ; 478
    dta d'Jorge       '    ; 479
    dta d'Walery      '    ; 480
    dta d'Vadim       '    ; 481
    dta d'Ruben       '    ; 482
    dta d'Tom         '    ; 483
    dta d'Tobias      '    ; 484
    dta d'Michel      '    ; 485
    dta d'Axel        '    ; 486
    dta d'Ibrahim     '    ; 487
    dta d'Dylan       '    ; 488
    dta d'Casper      '    ; 489
    dta d'Alberto     '    ; 490
    dta d'Alejandro   '    ; 491
    dta d'Giovanni    '    ; 492
    dta d'Iwan        '    ; 493
    dta d'Fabio       '    ; 494
    dta d'Joel        '    ; 495
    dta d'Sergey      '    ; 496
    dta d'Miguel      '    ; 497
    dta d'Cezariusz   '    ; 498
    dta d'Steven      '    ; 499
    dta d'Tymofii     '    ; 500

NAMES_BABSKIE
    dta d'Anna        '    ; 1
    dta d'Maria       '    ; 2
    dta d'Katarzyna   '    ; 3
    dta d'Małgorzata  '    ; 4
    dta d'Agnieszka   '    ; 5
    dta d'Barbara     '    ; 6
    dta d'Ewa         '    ; 7
    dta d'Krystyna    '    ; 8
    dta d'Elżbieta    '    ; 9
    dta d'Magdalena   '    ; 10
    dta d'Joanna      '    ; 11
    dta d'Zofia       '    ; 12
    dta d'Aleksandra  '    ; 13
    dta d'Monika      '    ; 14
    dta d'Teresa      '    ; 15
    dta d'Danuta      '    ; 16
    dta d'Natalia     '    ; 17
    dta d'Karolina    '    ; 18
    dta d'Marta       '    ; 19
    dta d'Julia       '    ; 20
    dta d'Beata       '    ; 21
    dta d'Dorota      '    ; 22
    dta d'Janina      '    ; 23
    dta d'Jadwiga     '    ; 24
    dta d'Halina      '    ; 25
    dta d'Jolanta     '    ; 26
    dta d'Alicja      '    ; 27
    dta d'Irena       '    ; 28
    dta d'Grażyna     '    ; 29
    dta d'Iwona       '    ; 30
    dta d'Paulina     '    ; 31
    dta d'Justyna     '    ; 32
    dta d'Bożena      '    ; 33
    dta d'Zuzanna     '    ; 34
    dta d'Wiktoria    '    ; 35
    dta d'Urszula     '    ; 36
    dta d'Renata      '    ; 37
    dta d'Helena      '    ; 38
    dta d'Sylwia      '    ; 39
    dta d'Agata       '    ; 40
    dta d'Hanna       '    ; 41
    dta d'Patrycja    '    ; 42
    dta d'Izabela     '    ; 43
    dta d'Maja        '    ; 44
    dta d'Aneta       '    ; 45
    dta d'Emilia      '    ; 46
    dta d'Weronika    '    ; 47
    dta d'Ewelina     '    ; 48
    dta d'Marianna    '    ; 49
    dta d'Oliwia      '    ; 50
    dta d'Martyna     '    ; 51
    dta d'Klaudia     '    ; 52
    dta d'Stanisława  '    ; 53
    dta d'Marzena     '    ; 54
    dta d'Gabriela    '    ; 55
    dta d'Dominika    '    ; 56
    dta d'Kinga       '    ; 57
    dta d'Edyta       '    ; 58
    dta d'Wiesława    '    ; 59
    dta d'Lena        '    ; 60
    dta d'Amelia      '    ; 61
    dta d'Kamila      '    ; 62
    dta d'Wanda       '    ; 63
    dta d'Alina       '    ; 64
    dta d'Lucyna      '    ; 65
    dta d'Lidia       '    ; 66
    dta d'Mariola     '    ; 67
    dta d'Mirosława   '    ; 68
    dta d'Wioletta    '    ; 69
    dta d'Nikola      '    ; 70
    dta d'Daria       '    ; 71
    dta d'Milena      '    ; 72
    dta d'Kazimiera   '    ; 73
    dta d'Angelika    '    ; 74
    dta d'Genowefa    '    ; 75
    dta d'Bogumiła    '    ; 76
    dta d'Józefa      '    ; 77
    dta d'Antonina    '    ; 78
    dta d'Olga        '    ; 79
    dta d'Henryka     '    ; 80
    dta d'Stefania    '    ; 81
    dta d'Sandra      '    ; 82
    dta d'Laura       '    ; 83
    dta d'Ilona       '    ; 84
    dta d'Sabina      '    ; 85
    dta d'Bogusława   '    ; 86
    dta d'Regina      '    ; 87
    dta d'Marlena     '    ; 88
    dta d'Michalina   '    ; 89
    dta d'Władysława  '    ; 90
    dta d'Czesława    '    ; 91
    dta d'Łucja       '    ; 92
    dta d'Anita       '    ; 93
    dta d'Nadia       '    ; 94
    dta d'Kornelia    '    ; 95
    dta d'Aniela      '    ; 96
    dta d'Jagoda      '    ; 97
    dta d'Iga         '    ; 98
    dta d'Nina        '    ; 99
    dta d'Liliana     '    ; 100
    dta d'Wioleta     '    ; 101
    dta d'Marcelina   '    ; 102
    dta d'Cecylia     '    ; 103
    dta d'Roksana     '    ; 104
    dta d'Adrianna    '    ; 105
    dta d'Dagmara     '    ; 106
    dta d'Karina      '    ; 107
    dta d'Pola        '    ; 108
    dta d'Leokadia    '    ; 109
    dta d'Malwina     '    ; 110
    dta d'Zdzisława   '    ; 111
    dta d'Bronisława  '    ; 112
    dta d'Sara        '    ; 113
    dta d'Żaneta      '    ; 114
    dta d'Eugenia     '    ; 115
    dta d'Eliza       '    ; 116
    dta d'Bernadeta   '    ; 117
    dta d'Róża        '    ; 118
    dta d'Daniela     '    ; 119
    dta d'Julita      '    ; 120
    dta d'Aldona      '    ; 121
    dta d'Kaja        '    ; 122
    dta d'Anastazja   '    ; 123
    dta d'Rozalia     '    ; 124
    dta d'Violetta    '    ; 125
    dta d'Celina      '    ; 126
    dta d'Magda       '    ; 127
    dta d'Tetiana     '    ; 128
    dta d'Blanka      '    ; 129
    dta d'Klara       '    ; 130
    dta d'Nataliia    '    ; 131
    dta d'Honorata    '    ; 132
    dta d'Olena       '    ; 133
    dta d'Iryna       '    ; 134
    dta d'Diana       '    ; 135
    dta d'Oksana      '    ; 136
    dta d'Gertruda    '    ; 137
    dta d'Adriana     '    ; 138
    dta d'Brygida     '    ; 139
    dta d'Lilianna    '    ; 140
    dta d'Paula       '    ; 141
    dta d'Mieczysława '    ; 142
    dta d'Izabella    '    ; 143
    dta d'Matylda     '    ; 144
    dta d'Bożenna     '    ; 145
    dta d'Svitlana    '    ; 146
    dta d'Aurelia     '    ; 147
    dta d'Elwira      '    ; 148
    dta d'Olha        '    ; 149
    dta d'Marzanna    '    ; 150
    dta d'Marika      '    ; 151
    dta d'Sonia       '    ; 152
    dta d'Kalina      '    ; 153
    dta d'Andżelika   '    ; 154
    dta d'Arleta      '    ; 155
    dta d'Franciszka  '    ; 156
    dta d'Mariia      '    ; 157
    dta d'Adela       '    ; 158
    dta d'Olivia      '    ; 159
    dta d'Nela        '    ; 160
    dta d'Alfreda     '    ; 161
    dta d'Yuliia      '    ; 162
    dta d'Luiza       '    ; 163
    dta d'Judyta      '    ; 164
    dta d'Viktoriia   '    ; 165
    dta d'Nicola      '    ; 166
    dta d'Natasza     '    ; 167
    dta d'Nicole      '    ; 168
    dta d'Tatiana     '    ; 169
    dta d'Kateryna    '    ; 170
    dta d'Jowita      '    ; 171
    dta d'Liudmyla    '    ; 172
    dta d'Romana      '    ; 173
    dta d'Ludwika     '    ; 174
    dta d'Anastasiia  '    ; 175
    dta d'Victoria    '    ; 176
    dta d'Apolonia    '    ; 177
    dta d'Eleonora    '    ; 178
    dta d'Wacława     '    ; 179
    dta d'Julianna    '    ; 180
    dta d'Vanessa     '    ; 181
    dta d'Marzenna    '    ; 182
    dta d'Zenona      '    ; 183
    dta d'Jessica     '    ; 184
    dta d'Tamara      '    ; 185
    dta d'Halyna      '    ; 186
    dta d'Inga        '    ; 187
    dta d'Estera      '    ; 188
    dta d'Hildegarda  '    ; 189
    dta d'Bernadetta  '    ; 190
    dta d'Walentyna   '    ; 191
    dta d'Ada         '    ; 192
    dta d'Melania     '    ; 193
    dta d'Zenobia     '    ; 194
    dta d'Liwia       '    ; 195
    dta d'Felicja     '    ; 196
    dta d'Maryna      '    ; 197
    dta d'Donata      '    ; 198
    dta d'Ludmiła     '    ; 199
    dta d'Romualda    '    ; 200
    dta d'Anetta      '    ; 201
    dta d'Valentyna   '    ; 202
    dta d'Pelagia     '    ; 203
    dta d'Gizela      '    ; 204
    dta d'Otylia      '    ; 205
    dta d'Bianka      '    ; 206
    dta d'Amanda      '    ; 207
    dta d'Nadiia      '    ; 208
    dta d'Irmina      '    ; 209
    dta d'Eryka       '    ; 210
    dta d'Mia         '    ; 211
    dta d'Elena       '    ; 212
    dta d'Inna        '    ; 213
    dta d'Larysa      '    ; 214
    dta d'Waleria     '    ; 215
    dta d'Sławomira   '    ; 216
    dta d'Bernarda    '    ; 217
    dta d'Rita        '    ; 218
    dta d'Teodozja    '    ; 219
    dta d'Longina     '    ; 220
    dta d'Lilla       '    ; 221
    dta d'Teodora     '    ; 222
    dta d'Lilia       '    ; 223
    dta d'Maya        '    ; 224
    dta d'Ryszarda    '    ; 225
    dta d'Ida         '    ; 226
    dta d'Adelajda    '    ; 227
    dta d'Albina      '    ; 228
    dta d'Emma        '    ; 229
    dta d'Oleksandra  '    ; 230
    dta d'Mirela      '    ; 231
    dta d'Kamilla     '    ; 232
    dta d'Liubov      '    ; 233
    dta d'Feliksa     '    ; 234
    dta d'Alla        '    ; 235
    dta d'Yana        '    ; 236
    dta d'Faustyna    '    ; 237
    dta d'Olimpia     '    ; 238
    dta d'Lucja       '    ; 239
    dta d'Samanta     '    ; 240
    dta d'Leonarda    '    ; 241
    dta d'Zyta        '    ; 242
    dta d'Lila        '    ; 243
    dta d'Maryla      '    ; 244
    dta d'Marcela     '    ; 245
    dta d'Alexandra   '    ; 246
    dta d'Angelina    '    ; 247
    dta d'Liliia      '    ; 248
    dta d'Viktoria    '    ; 249
    dta d'Ksenia      '    ; 250
    dta d'Oktawia     '    ; 251
    dta d'Sofia       '    ; 252
    dta d'Pamela      '    ; 253
    dta d'Konstancja  '    ; 254
    dta d'Bolesława   '    ; 255
    dta d'Wanessa     '    ; 256
    dta d'Alona       '    ; 257
    dta d'Salomea     '    ; 258
    dta d'Bogna       '    ; 259
    dta d'Veronika    '    ; 260
    dta d'Nadzieja    '    ; 261
    dta d'Elfryda     '    ; 262
    dta d'Mirella     '    ; 263
    dta d'Claudia     '    ; 264
    dta d'Mariana     '    ; 265
    dta d'Edwarda     '    ; 266
    dta d'Krzysztofa  '    ; 267
    dta d'Sofiia      '    ; 268
    dta d'Zoja        '    ; 269
    dta d'Gaja        '    ; 270
    dta d'Ivanna      '    ; 271
    dta d'Noemi       '    ; 272
    dta d'Inez        '    ; 273
    dta d'Khrystyna   '    ; 274
    dta d'Valeriia    '    ; 275
    dta d'Edeltrauda  '    ; 276
    dta d'Jagna       '    ; 277
    dta d'Mariya      '    ; 278
    dta d'Nel         '    ; 279
    dta d'Sophie      '    ; 280
    dta d'Ola         '    ; 281
    dta d'Stella      '    ; 282
    dta d'Michelle    '    ; 283
    dta d'Emily       '    ; 284
    dta d'Angela      '    ; 285
    dta d'Nataliya    '    ; 286
    dta d'Lesia       '    ; 287
    dta d'Sarah       '    ; 288
    dta d'Vira        '    ; 289
    dta d'Wiera       '    ; 290
    dta d'Alena       '    ; 291
    dta d'Tola        '    ; 292
    dta d'Iza         '    ; 293
    dta d'Miriam      '    ; 294
    dta d'Arletta     '    ; 295
    dta d'Ruta        '    ; 296
    dta d'Ines        '    ; 297
    dta d'Marina      '    ; 298
    dta d'Helga       '    ; 299
    dta d'Klementyna  '    ; 300
    dta d'Klaudyna    '    ; 301
    dta d'Manuela     '    ; 302
    dta d'Roma        '    ; 303
    dta d'Gerda       '    ; 304
    dta d'Galyna      '    ; 305
    dta d'Irina       '    ; 306
    dta d'Natalie     '    ; 307
    dta d'Marietta    '    ; 308
    dta d'Lea         '    ; 309
    dta d'Jaśmina     '    ; 310
    dta d'Antonia     '    ; 311
    dta d'Yuliya      '    ; 312
    dta d'Teofila     '    ; 313
    dta d'Greta       '    ; 314
    dta d'Yevheniia   '    ; 315
    dta d'Irmgarda    '    ; 316
    dta d'Eva         '    ; 317
    dta d'Eulalia     '    ; 318
    dta d'Olesia      '    ; 319
    dta d'Bernardyna  '    ; 320
    dta d'Raisa       '    ; 321
    dta d'Yelyzaveta  '    ; 322
    dta d'Jarosława   '    ; 323
    dta d'Dobrosława  '    ; 324
    dta d'Florentyna  '    ; 325
    dta d'Erna        '    ; 326
    dta d'Ruslana     '    ; 327
    dta d'Andrea      '    ; 328
    dta d'Martina     '    ; 329
    dta d'Anastasiya  '    ; 330
    dta d'Erika       '    ; 331
    dta d'Ana         '    ; 332
    dta d'Tetyana     '    ; 333
    dta d'Polina      '    ; 334
    dta d'Luba        '    ; 335
    dta d'Hanka       '    ; 336
    dta d'Mila        '    ; 337
    dta d'Kunegunda   '    ; 338
    dta d'Wanesa      '    ; 339
    dta d'Nicol       '    ; 340
    dta d'Vita        '    ; 341
    dta d'Tatsiana    '    ; 342
    dta d'Sophia      '    ; 343
    dta d'Veronica    '    ; 344
    dta d'Dżesika     '    ; 345
    dta d'Iuliia      '    ; 346
    dta d'Linda       '    ; 347
    dta d'Lidiia      '    ; 348
    dta d'Marcjanna   '    ; 349
    dta d'Balbina     '    ; 350
    dta d'Wirginia    '    ; 351
    dta d'Seweryna    '    ; 352
    dta d'Kristina    '    ; 353
    dta d'Natallia    '    ; 354
    dta d'Majka       '    ; 355
    dta d'Ala         '    ; 356
    dta d'Jennifer    '    ; 357
    dta d'Myroslava   '    ; 358
    dta d'Marita      '    ; 359
    dta d'Nikol       '    ; 360
    dta d'Filomena    '    ; 361
    dta d'Patricia    '    ; 362
    dta d'Ganna       '    ; 363
    dta d'Livia       '    ; 364
    dta d'Malina      '    ; 365
    dta d'Marharyta   '    ; 366
    dta d'Zhanna      '    ; 367
    dta d'Karyna      '    ; 368
    dta d'Zinaida     '    ; 369
    dta d'Volha       '    ; 370
    dta d'Simona      '    ; 371
    dta d'Isabella    '    ; 372
    dta d'Dajana      '    ; 373
    dta d'Anastasia   '    ; 374
    dta d'Uliana      '    ; 375
    dta d'Lara        '    ; 376
    dta d'Galina      '    ; 377
    dta d'Anika       '    ; 378
    dta d'Gloria      '    ; 379
    dta d'Emanuela    '    ; 380
    dta d'Anzhela     '    ; 381
    dta d'Leontyna    '    ; 382
    dta d'Sabrina     '    ; 383
    dta d'Katsiaryna  '    ; 384
    dta d'Kornela     '    ; 385
    dta d'Benedykta   '    ; 386
    dta d'Berenika    '    ; 387
    dta d'Blandyna    '    ; 388
    dta d'Jana        '    ; 389
    dta d'Lubomira    '    ; 390
    dta d'Amalia      '    ; 391
    dta d'Nikoletta   '    ; 392
    dta d'Iwonna      '    ; 393
    dta d'Ramona      '    ; 394
    dta d'Mira        '    ; 395
    dta d'Ligia       '    ; 396
    dta d'Daryna      '    ; 397
    dta d'Caroline    '    ; 398
    dta d'Bogdana     '    ; 399
    dta d'Carmen      '    ; 400
    dta d'Żaklina     '    ; 401
    dta d'Gabryela    '    ; 402
    dta d'Hannah      '    ; 403
    dta d'Gabriella   '    ; 404
    dta d'Kseniia     '    ; 405
    dta d'Alisa       '    ; 406
    dta d'Ingeborga   '    ; 407
    dta d'Emila       '    ; 408
    dta d'Domicela    '    ; 409
    dta d'Ingrid      '    ; 410
    dta d'Nelly       '    ; 411
    dta d'Svetlana    '    ; 412
    dta d'Tekla       '    ; 413
    dta d'Dalia       '    ; 414
    dta d'Nadiya      '    ; 415
    dta d'Sybilla     '    ; 416
    dta d'Swietłana   '    ; 417
    dta d'Anhelina    '    ; 418
    dta d'Michaela    '    ; 419
    dta d'Naomi       '    ; 420
    dta d'Irma        '    ; 421
    dta d'Celestyna   '    ; 422
    dta d'Lyudmyla    '    ; 423
    dta d'Alice       '    ; 424
    dta d'Lily        '    ; 425
    dta d'Alicia      '    ; 426
    dta d'Elizabeth   '    ; 427
    dta d'Idalia      '    ; 428
    dta d'Gracjana    '    ; 429
    dta d'Leonia      '    ; 430
    dta d'Valentina   '    ; 431
    dta d'Sława       '    ; 432
    dta d'Roxana      '    ; 433
    dta d'Bernardeta  '    ; 434
    dta d'Bianca      '    ; 435
    dta d'Żanetta     '    ; 436
    dta d'Ina         '    ; 437
    dta d'Józefina    '    ; 438
    dta d'Margarita   '    ; 439
    dta d'Hana        '    ; 440
    dta d'Berta       '    ; 441
    dta d'Margareta   '    ; 442
    dta d'Darya       '    ; 443
    dta d'Liudmila    '    ; 444
    dta d'Violeta     '    ; 445
    dta d'Lyubov      '    ; 446
    dta d'Lilly       '    ; 447
    dta d'Kira        '    ; 448
    dta d'Zoriana     '    ; 449
    dta d'Inka        '    ; 450
    dta d'Benita      '    ; 451
    dta d'Dariia      '    ; 452
    dta d'Maryia      '    ; 453
    dta d'Sviatlana   '    ; 454
    dta d'Kaya        '    ; 455
    dta d'Ella        '    ; 456
    dta d'Marie       '    ; 457
    dta d'Monica      '    ; 458
    dta d'Carolina    '    ; 459
    dta d'Bohdana     '    ; 460
    dta d'Jesika      '    ; 461
    dta d'Ela         '    ; 462
    dta d'Abigail     '    ; 463
    dta d'Milana      '    ; 464
    dta d'Kasandra    '    ; 465
    dta d'Karin       '    ; 466
    dta d'Dobrawa     '    ; 467
    dta d'Eunika      '    ; 468
    dta d'Dobrochna   '    ; 469
    dta d'Jessika     '    ; 470
    dta d'Dagna       '    ; 471
    dta d'Augustyna   '    ; 472
    dta d'Ariana      '    ; 473
    dta d'Yaroslava   '    ; 474
    dta d'Oriana      '    ; 475
    dta d'Nelia       '    ; 476
    dta d'Viktoriya   '    ; 477
    dta d'Wilhelmina  '    ; 478
    dta d'Lesława     '    ; 479
    dta d'Eufemia     '    ; 480
    dta d'Ekaterina   '    ; 481
    dta d'Viktoryia   '    ; 482
    dta d'Nathalie    '    ; 483
    dta d'Melissa     '    ; 484
    dta d'Melisa      '    ; 485
    dta d'Julitta     '    ; 486
    dta d'Petronela   '    ; 487
    dta d'Sylwestra   '    ; 488
    dta d'Snizhana    '    ; 489
    dta d'Ernestyna   '    ; 490
    dta d'Fatima      '    ; 491
    dta d'Giulia      '    ; 492
    dta d'Marieta     '    ; 493
    dta d'Lina        '    ; 494
    dta d'Vladyslava  '    ; 495
    dta d'Jasmina     '    ; 496
    dta d'Zoe         '    ; 497
    dta d'Anzhelika   '    ; 498
    dta d'Lisa        '    ; 499
    dta d'Nikolina    '    ; 500

